# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Mengrui Ni"
description: > # this means to ignore newlines until "email:"
   Python Developer - New York City

email: mengrui_ni@brown.edu
#blog logo
logo: "/assets/images/p1791101068.jpg"
# blog cover
cover: "/assets/images/hutongs-5.jpg"

name: 'Mengrui Ni'
author: 'Mengrui Ni'
author_image: "/assets/images/p1791101068.jpg"

paginate:	5

url: "https://mninmr.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/SamuelPeters15
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mninmr
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
